export enum PageRoutes {
  Home = "/",
  Notifications = "/notificaciones",
  Owner_Environments = "/mis-ambientes",
  Owner_Single_Environment = "/mi-ambiente",
  Booking = "/reservas",
  Book = "/reservar",
  Profile = "/perfil",
  Shots_360 = "/admin/capturas360",
  Create_Virtual_Tour = "/admin/capturas360/crear",
  Calendar = "/calendario",
  Debts = "/admin/deudas",
  Admin_Payments = "admin/pagos",
  Search = "/buscar",
  Environment_Details = "/detalles",
  LogIn = "/ingresar",
  SignUp = "/registro",
  New_Environment = "/nuevo-ambiente",
  Incomes = "/ingresos",
  Received_Payments = "/pagos-recibidos",
}
