export enum PageRoutes {
  Home = "/",
  Notifications = "/notificaciones",
  Owner_Environments = "/mis-ambientes",
  Owner_Single_Environment = "/mi-ambiente",
  Booking = "/reservas",
  Book = "/reservar",
  Profile = "/perfil",
  Shots_360 = "/capturas360",
  Create_Virtual_Tour = "/capturas360/crear",
  Calendar = "/calendario",
  Debts = "/deudas",
  Search = "/buscar",
  Environment_Details = "/detalles",
  LogIn = "/ingresar",
  SignUp = "/registro",
  New_Environment = "/nuevo-ambiente",
}
